# Generated by Django 2.2.4 on 2019-08-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')], default='Medium', max_length=255),
        ),
    ]
